name: Test Allure Report Publisher

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test-allure-report-publisher:
    runs-on: ubuntu-latest
    name: Test Allure Report Publisher Action

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Build TypeScript
        run: yarn build

      - name: Run Allure Action
        uses: ./
        with:
          working-directory: "."

      - name: Check Action Output
        run: |
          echo "If the action found published reports, their URLs should be listed above."
